version: '3'

services:
  magento:
    image: michielgerritsen/magento-project-community-edition:${PHP_VERSION}-magento${MAGENTO_VERSION}-sample-data
    container_name: magento-project-community-edition
    environment:
      - VIRTUAL_HOST=magento.test
      - MOLLIE_API_KEY_TEST
    volumes:
      - ../../../magento-logs:/data/var/log
      - ./magento/configure-mollie.sh:/data/configure-mollie.sh
    depends_on:
      - ngrok

  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - ./nginx-proxy/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx-proxy/magento.test.crt:/etc/nginx/certs/magento.test.crt
      - ./nginx-proxy/magento.test.key:/etc/nginx/certs/magento.test.key
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ngrok:
    image: ngrok/ngrok:latest
    command: http http://magento
    environment:
      - NGROK_AUTHTOKEN

  e2e:
    build: ./e2e
    container_name: e2e
    links:
      - "nginx-proxy:magento.test"
    environment:
      - CYPRESS_TESTRAIL_DOMAIN
      - CYPRESS_TESTRAIL_USERNAME
      - CYPRESS_TESTRAIL_PASSWORD
      - CYPRESS_TESTRAIL_PROJECT_ID
      - CYPRESS_TESTRAIL_MILESTONE_ID
      - CYPRESS_TESTRAIL_RUN_NAME
      - CYPRESS_TESTRAIL_RUN_CLOSE
      - CYPRESS_baseUrl=https://magento.test
    volumes:
      - ./../../../Test/End-2-end/cypress:/e2e/cypress
      - ./../../../Test/End-2-end/cypress.config.js:/e2e/cypress.config.js
      - ./../../../Test/End-2-end/webpack.config.js:/e2e/webpack.config.js
